<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="xacros/robot_paras.xacro" />

    <gazebo>
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
            <right_joint>body_to_rw</right_joint>
            <left_joint>body_to_lw</left_joint>

            <wheel_separation>${body_box_size_x + wheel_length + wheel_offset}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>

            <max_velocity>4</max_velocity>
            <max_linear_acceleration>10</max_linear_acceleration>

            <topic>cmd_vel</topic>
        </plugin>

        <plugin
            filename="gz-sim-odometry-publisher-system"
            name="gz::sim::systems::OdometryPublisher">
            <odom_frame>odom</odom_frame>
            <robot_base_frame>base_link</robot_base_frame>
            <odom_publish_frequency>50</odom_publish_frequency>
            <odom_topic>/odom</odom_topic>
            <tf_topic>/tf</tf_topic>
            <dimensions>2</dimensions>
        </plugin>

        <plugin filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">
            <topic>joint_states</topic>
            <joint_name>body_to_rw</joint_name>
            <joint_name>body_to_lw</joint_name>
        </plugin>
    </gazebo>

    <gazebo reference="imu_link">
        <sensor name="imu" type="imu">
            <always_on>true</always_on>
            <update_rate>200</update_rate>
            <visualize>true</visualize>
            <topic>imu</topic>
            <enable_metrics>true</enable_metrics>
            <gz_frame_id>imu_link</gz_frame_id>
        </sensor>
    </gazebo>

    <gazebo reference="lidar_frame">
        <sensor name="lidar" type="gpu_lidar">
            <pose relative_to="lidar_frame">0 0 0 0 0 0</pose>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>5</update_rate>
            <topic>scan</topic>
            <gz_frame_id>lidar_frame</gz_frame_id>

            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>

                <range>
                    <min>0.05</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>

                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
        </sensor>
    </gazebo>
    <!-- <gazebo reference="lidar_frame">
        <sensor name="lidar" type="gpu_lidar">
            <pose> 0 0 0 0 0 0 </pose>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <topic>scan</topic>
            <gz_frame_id>lidar_frame</gz_frame_id>
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.05</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
                <frame_id>lidar_frame</frame_id>
            </ray>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo> -->

</robot>